// <copyright file="GlobalSuppressions.cs" company="Microsoft">
// Copyright (c) Microsoft. All rights reserved.
// </copyright>

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1636:File header copyright text should match", Justification = "done", Scope = "namespace", Target = "~N:CalculatorChatBot")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1636:File header copyright text should match", Justification = "done")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1638:File header file name documentation should match file name", Justification = "done", Scope = "namespace", Target = "~N:CalculatorChatBot.Helpers.AdaptiveCards")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "Acceptable coding standards.", Scope = "member", Target = "~M:CalculatorChatBot.Bots.CalculatorBot.OnMessageActivityAsync(Microsoft.Bot.Builder.ITurnContext{Microsoft.Bot.Schema.IMessageActivity},System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "Acceptable coding standards.", Scope = "member", Target = "~M:CalculatorChatBot.Bots.CalculatorBot.OnConversationUpdateActivityAsync(Microsoft.Bot.Builder.ITurnContext{Microsoft.Bot.Schema.IConversationUpdateActivity},System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Acceptable coding standards.", Scope = "member", Target = "~M:CalculatorChatBot.OperationsLib.Statistic.CalculateMean(System.String,Microsoft.Bot.Builder.ITurnContext,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Acceptable coding standards.", Scope = "member", Target = "~M:CalculatorChatBot.OperationsLib.Statistic.CalculateMedian(System.String,Microsoft.Bot.Builder.ITurnContext,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Acceptable coding standards.", Scope = "member", Target = "~M:CalculatorChatBot.OperationsLib.Statistic.CalculateRange(System.String,Microsoft.Bot.Builder.ITurnContext,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "Acceptable coding standards.", Scope = "member", Target = "~M:CalculatorChatBot.OperationsLib.Statistic.CalculateMean(System.String,Microsoft.Bot.Builder.ITurnContext,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "Acceptable coding standards.", Scope = "member", Target = "~M:CalculatorChatBot.OperationsLib.Statistic.CalculateMedian(System.String,Microsoft.Bot.Builder.ITurnContext,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "Acceptable coding standards.", Scope = "member", Target = "~M:CalculatorChatBot.OperationsLib.Statistic.CalculateRange(System.String,Microsoft.Bot.Builder.ITurnContext,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Acceptable coding standards.", Scope = "member", Target = "~M:CalculatorChatBot.Startup.Configure(Microsoft.AspNetCore.Builder.IApplicationBuilder,Microsoft.AspNetCore.Hosting.IHostingEnvironment)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Acceptable coding standards.", Scope = "member", Target = "~M:CalculatorChatBot.Startup.ConfigureServices(Microsoft.Extensions.DependencyInjection.IServiceCollection)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "Acceptable coding standards.", Scope = "member", Target = "~M:CalculatorChatBot.OperationsLib.Statistic.CalculateMode(System.String,Microsoft.Bot.Builder.ITurnContext,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "Acceptable coding standards.", Scope = "member", Target = "~M:CalculatorChatBot.OperationsLib.Statistic.CalculateVariance(System.String,Microsoft.Bot.Builder.ITurnContext,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "Acceptable coding standards.", Scope = "member", Target = "~M:CalculatorChatBot.OperationsLib.Geometric.CalculateDiscriminant(System.String,Microsoft.Bot.Builder.ITurnContext,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]